// flow-typed signature: 93c707d4fac04a73e1d5faa22e44a2c2
// flow-typed version: <<STUB>>/git-format-staged_v^1.1.0/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'git-format-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'git-format-staged' {
  declare module.exports: any;
}
